### ISSUE TITLE
Unhanded `error` events

### ISSUE THREAD

**Issue by kittykatattack** [moarwick/elm-webpack-starter#5]
Hello!

I've followed your directions for installing and running elm-webpack-starter and am receiving this error message when I run `npm start`

```
WEBPACK GO!
Serving locally...
http://localhost:8080/
webpack result is served from /
content is served from /Users/rexvanderspuy/elm/elm-webpack-starter
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/rexvanderspuy/elm/elm-webpack-starter/node_modules/elm/Elm-Platform/0.16.0/.cabal-sandbox/bin/elm-make ENOENT
    at exports._errnoException (util.js:860:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
    at Function.Module.runMain (module.js:459:11)
    at startup (node.js:136:18)
    at node.js:972:3
```

I'm on OS X El Capitan. 
Do you have any idea what might be wong?

**Comment by moarwick** [comment]
Hmm, perhaps your Node version? (I'm on 5.1) In any case, just pushed a fairly large update. It might be best to re-clone and try `npm install` again. Hope it helps!

**Comment by kittykatattack** [comment]
No problem, it's working now :)
